version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: restpilot
      MYSQL_PASSWORD: restpilot
      MYSQL_DATABASE: restpilot
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15673:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-microservice:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=restpilot
      - DB_PASSWORD=restpilot
      - DB_NAME=restpilot
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  graphql-microservice:
    build:
      context: ./graphql-microservice
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mariadb_data:
