version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=restpilot-auth-dev
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth-microservice:/app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mariadb:3306/restpilot-auth-dev
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: yarn start:dev

  graphql:
    build:
      context: ./graphql-microservice
      dockerfile: Dockerfile.dev
    volumes:
      - ./graphql-microservice:/app
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mariadb:3306/restpilot-graphql-dev
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: yarn start:dev

  orders:
    build:
      context: ./orders-microservice
      dockerfile: Dockerfile.dev
    volumes:
      - ./orders-microservice:/app
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mariadb:3306/restpilot-orders-dev
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: yarn start:dev

volumes:
  mariadb_data:
